# Generated by Django 4.0.3 on 2022-03-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='Subscriber',
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ('name',), 'verbose_name': 'Подписчик', 'verbose_name_plural': 'Подписчик'},
        ),
    ]
