# Generated by Django 4.0.3 on 2022-03-26 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_options_product_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='ProductInOrder',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
