# Generated by Django 4.0.3 on 2022-03-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_productcategory_product_discount_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='category',
        ),
    ]
